[build]
  command = "yarn cache clean && yarn add --os=linux --cpu=x64 sharp@0.32 --ignore-engines && yarn build"
  publish = ".next"
  framework = "next"


[functions]
  node_bundler = "esbuild"
  external_node_modules = ["libsql","sharp"]
  included_files = ["node_modules/sharp/**/*"]

[dev]
  command = "npm run dev:preview"
  framework = "next"
  targetPort = 3000
  port = 443
  publish = "publish"
  [dev.https]
    certFile = "certificates/custom-proyect-1.jeelidev.uk.pem"
    keyFile = "certificates/custom-proyect-1.jeelidev.uk-key.pem"
