[build]
  command = "pnpm add sharp && pnpm build"
  publish = ".next"
  framework = "next"


[functions]
  node_bundler = "esbuild"
  external_node_modules = ["libsql" , "sharp"]
  included_files = ["node_modules/sharp/**/*"]

  [functions."*"]
    external_node_modules = ["libsql", "sharp"]
    included_files = [
      "node_modules/sharp/**/*",
    ]

[dev]
  command = "npm run dev:preview"
  framework = "next"
  targetPort = 3000
  port = 443
  publish = "publish"
  [dev.https]
    certFile = "certificates/custom-proyect-1.jeelidev.uk.pem"
    keyFile = "certificates/custom-proyect-1.jeelidev.uk-key.pem"
    
[[plugins]]
package = "@netlify/plugin-nextjs"